//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pill_Reminder_System_api24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.M_Schedule = new HashSet<M_Schedule>();
            this.M_Schedule2 = new HashSet<M_Schedule2>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<int> no_dosage { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<int> caretaker_id { get; set; }
        public byte[] image { get; set; }
        public string color { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string image_path { get; set; }
    
        public virtual CareTaker CareTaker { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Schedule> M_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Schedule2> M_Schedule2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
