//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pill_Reminder_System_api24.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pill_Reminder_SystemEntities1 : DbContext
    {
        public Pill_Reminder_SystemEntities1()
            : base("name=Pill_Reminder_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareTaker> CareTakers { get; set; }
        public virtual DbSet<Dispenser> Dispensers { get; set; }
        public virtual DbSet<Dispenser2> Dispenser2 { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<M_Schedule> M_Schedule { get; set; }
        public virtual DbSet<M_Schedule2> M_Schedule2 { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<P_Schedule> P_Schedule { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Patient_CareTaker> Patient_CareTaker { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
    }
}
