//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pill_Reminder_System_api24.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_CareTaker
    {
        public int id { get; set; }
        public Nullable<int> caretaker_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> priority { get; set; }
        public string status { get; set; }
        public string status2 { get; set; }
    
        public virtual CareTaker CareTaker { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
